### ISSUE TITLE
Is this indentional?

### ISSUE THREAD

**Issue by ChiaMineJP** [Chia-Network/clvm#97]
`int_to_bytes` at `casts.py` seems adding extra byte.

```python
def int_to_bytes(v):
    byte_count = (v.bit_length() + 8) >> 3 # Should be (v.bit_length() + 7) >> 3
    if v == 0:
        return b""
    r = v.to_bytes(byte_count, "big", signed=True)
    # make sure the string returned is minimal
    # ie. no leading 00 or ff bytes that are unnecessary
    while len(r) > 1 and r[0] == (0xFF if r[1] & 0x80 else 0):
        r = r[1:]
    return r
```

Because of the above implementation, `str(SExp.to(131))` returns  `820083` as a serialized value, where `8183` is more byte-efficient.
*(integer 131 is represented `83` as a hex string. Cleary this is 1-byte value.)*
*More directly, `int_to_bytes(131) == b'\x00\x83'` where `b'\x83'` is more byte-efficient*

**Comment by richardkiss** [comment]
`0x83` represents -125.

**Comment by arvidn** [comment]
in other words: "Yes, it is intentional". Integers are represented in 2's complement, hence if the most significant bit is set, it is a negative number.

**Comment by ChiaMineJP** [comment]
Thank you both to teach me.
So leading `0x00` of `0x0083` works as, say, sign-'byte'.

Oh, I confirmd `int_to_bytes(-125) == b'\x83`
Wonderful.

By the way, I really thank you all for making your works to be open source. This is really great.
